baseurl = "http://blog.tuxable.co.uk/"
languageCode = "en-gb"
title = "Tuxable Blog"
theme = "beautifulhugo"
pygmentsUseClasses = true
pygmentCodeFences = true
disqusShortname = "jackmitchblog"
#googleAnalytics = "XXX"

[Params]
  subtitle = "Penguin & Chips"
  logo = "images/tuxable-logo.png"
  favicon = "favicon.ico"
  commit = false

[Author]
  name = "Jack Mitchell"
  email = "blog@embed.me.uk"
  googleplus = "+JackMitchell"
  github = "jackmitch"
  linkedin = "jackmitch"
  reddit = ""
  twitter = ""
  xing = ""
  facebook = ""
  stackoverflow = ""
  snapchat = ""
  instagram = ""
  youtube = ""
  soundcloud = ""
  spotify = ""
  bandcamp = ""
  itchio = ""

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Consulting"
    url = "/page/consulting/"
    weight = 2

[[menu.main]]
    identifier = "projects"
    name = "Projects"
    weight = 5

[[menu.main]]
    parent = "projects"
    name = "libsoc"
    url = "http://www.github.com/jackmitch/libsoc.git"
    weight = 1

[[menu.main]]
    parent = "projects"
    name = "Tinker BSP"
    url = "http://www.github.com/jackmitch/meta-tinker.git"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4
